version: "3.9"

services:
  orders-api:
    build:
      context: .
      args:
        DEV: false
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
