version: "3.9"

services:
  chatbot:
    build:
      context: .
      args:
        DEV: true
    env_file:
      - .env
    volumes:
      - ./src/app:/app/app
    ports:
      - "${APP_PORT}:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
